- name: Demo on variables
  hosts: localhost
  tasks:
    - name: Print Hello World
      ansible.builtin.debug:
        msg: Hello World

- name: Demo on variables
  hosts: localhost
  vars:
    URL: example.com
  tasks:
    - name: Print a variable
      ansible.builtin.debug:
        msg: "{{ URL }}"

- name: Demo on task variables
  hosts: localhost
  vars:
    URL: play.example.com
  tasks:
    - name: Print a task variable
      ansible.builtin.debug:
        msg: "{{ URL }}"
      vars:
        URL: task.example.com

    - name: Print a play variable
      ansible.builtin.debug:
        msg: "{ URL }"

# The variable should be inside double or single quotes, because it will fail in some instances if a double quote is not used.

# In the key:value, if the value is only a variable or when it begins with a variable it will fail.