- name: Print Used Memory
  hosts: localhost
  tasks:
    - name: Memory Good
      ansible.builtin.debug:
        msg: '{{ ansible_memory_mb["real"] }}'

    - name: Used Memory
      ansible.builtin.debug:
        msg: '{{ ansible_memory_mb["real"]["used"] }}'


#  when: ansible_memory_mb["real"]["used"] |int < 50