- name: Declare a variable
  ansible.builtin.debug:
    msg: "URL = {{URL}}"

#- name: Copy file
#  ansible.builtin.copy:
#    src: test.txt
#    dest: /tmp/test.txt

- name: Copy file
  ansible.builtin.template:
    src: test.txt
    dest: /tmp/test.txt
